# Generated by Django 6.0 on 2025-12-21 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0002_remove_coffee_quantity_coffee_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coffee',
            name='description',
        ),
        migrations.RemoveField(
            model_name='coffee',
            name='image',
        ),
        migrations.AddField(
            model_name='coffee',
            name='image_url',
            field=models.URLField(default='https://images.unsplash.com/photo-1630021439100-74a32ab42d3e?q=80&w=824&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coffee',
            name='price',
            field=models.IntegerField(),
        ),
    ]
