# Generated by Django 6.0 on 2025-12-23 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0005_rename_created_at_order_ordered_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffee',
            name='image',
            field=models.URLField(default='https://images.unsplash.com/photo-1509042239860-f550ce710b93'),
            preserve_default=False,
        ),
    ]
