# Generated by Django 6.0 on 2025-12-23 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0007_menuitem_remove_order_item_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='image',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='image_url',
            field=models.URLField(default='https://images.unsplash.com/photo-1708430651927-20e2e1f1e8f7?q=80&w=627&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D', max_length=500),
            preserve_default=False,
        ),
    ]
