# Generated by Django 6.0 on 2025-12-23 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0011_alter_menuitem_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='category',
            field=models.CharField(choices=[('coffee', 'Coffee'), ('snack', 'Snack')], default='coffee', max_length=20),
        ),
    ]
